version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - frontend_dist:/app/frontend/dist

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    volumes:
      - frontend_dist:/app/web_app/static
      

volumes:
  frontend_dist:
