name: Deploy Cloud Run

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

env:
  SERVICE_NAME: privsyn-tabular
  REGION: us-east4
  PROJECT_ID: gen-lang-client-0649776758
  IMAGE: gcr.io/gen-lang-client-0649776758/privsyn-tabular

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: beta

      - name: Build and push container image
        run: |
          set -euo pipefail
          OPERATION=$(gcloud builds submit \
            --project "${PROJECT_ID}" \
            --tag "${IMAGE}" \
            --async \
            --format='value(name)')
          echo "Started Cloud Build operation: ${OPERATION}"
          gcloud builds operations wait "${OPERATION}" --project "${PROJECT_ID}"
          BUILD_ID=$(basename "${OPERATION}")
          STATUS=$(gcloud builds describe "${BUILD_ID}" --project "${PROJECT_ID}" --format='value(status)')
          echo "Cloud Build finished with status: ${STATUS}"
          if [ "${STATUS}" != "SUCCESS" ]; then
            echo "Cloud Build failed" >&2
            exit 1
          fi

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${SERVICE_NAME}" \
            --image "${IMAGE}" \
            --region "${REGION}" \
            --platform managed \
            --allow-unauthenticated
